### ISSUE TITLE
Existing PRTG Clone Instructions?

### ISSUE THREAD

**Issue by JustinGrote** [lordmilko/PrtgDocker#1]
This is rad. Do you have any instructions learned for cloning an existing PRTG installation into the docker?

My ideal use case is to snapshot a PRTG instance into a docker container so that I can then run the historical data extraction to SQL without impacting production. 

I'm doing this today with some complicated VSS and Rsync to a standby VM server, but with this I could use Azure Container Instances, spin up multiple copies of the same instance and pull in parallel from all of them to vastly speed up this process.

**Comment by lordmilko** [comment]
The purpose of this is to speed up the process of running PrtgAPI's integration tests. Currently these take 2.5 hours to run; my plan is to set up a Scheduled Task running on my current CI server that copies any new installers from my existing installer archiver system, which are then automatically converted into containers and pushed to Docker Hub.

The existing PrtgAPI Integration Test Settings file can be configured to specify whether you want to run against a normal CI server or to use Docker. When Docker is selected, a number of Docker containers will automatically be provisioned based on the latest image available, and then various config files are copied into the volume of the container from the host server (such as the PRTG Configuration.dat file) and then some hacks are applied to various config files to work around issues that are present inside of Docker but not outside of it (e.g. all my NIC sensors break, the System Information tab in PRTG can't get Hardware info). The containers will then function as a *pool*; all of the tests will be run in parallel, and if a container is not available, tests will block until another test has completed

To work around the lack of historical information inside the Docker image (which unlike my existing setup, isn't always running) I have reversed engineered the binary *.prd file format PRTG uses for storing sensor channel historical information. I will then programmatically synthesize all of the required historical data that would be required to complete my integration tests. I have also had a look at the *.db file format used for storing sensor logs, and it seems like it will be easy enough to reverse as well.

I am programmatically manipulating the Docker server using [Docker.DotNet](https://github.com/microsoft/Docker.DotNet) coupled with my existing impersonation techniques for fiddling with the filesystem of a remote computer that isn't on my domain.

In your scenario, I would say simply copying the config files into the container volume would be sufficient. If additional details on any of the information above would be of use to you, let me know!

Note: while I have just pushed an update to the config script that is used for creating the containers (to resolve some various issues I've discovered), the actual images on Docker Hub haven't been updated yet to reflect this

Regards,
lordmilko

**Comment by JustinGrote** [comment]
Do you have code or anything for the .prd reverse engineering? If I can just extract the historical data from that directly rather than having to go through PRTG's API that would be HUGE as I have lots of fanout stuff I can do with Azure Functions.

**Comment by lordmilko** [comment]
Here is the current state of both files. You probably just want to use the `SensorHistoryFile(string path)` constructor. You can probably use `Add-Type` or something to import these into PowerShell

Note; in my experience so far parsing a whole heap of *.prd files is pretty slow

Rename back to *.cs

[SensorHistoryFile.txt](https://github.com/lordmilko/PrtgDocker/files/4357266/SensorHistoryFile.txt)
[SensorHistoryFileChannel.txt](https://github.com/lordmilko/PrtgDocker/files/4357268/SensorHistoryFileChannel.txt)

**Comment by JustinGrote** [comment]
You rock! I'll experiment and report back. What I'd be able to do is set up an azure function to fan out a whole ton of powershell instances that each take a prd file, and then collate the results all back together (i'd probably dump it to CosmosDB now that it has the free autoscale tier). Should be fast and cheap.

**Comment by lordmilko** [comment]
PowerShell 5 will freak out at all the C# 6 features used (like interpolated strings), but under PowerShell Core looks like it's as simple as extracting the `SensorHistoryFileChannel` class and inserting that after the `SensorHistoryFile` class (but within the specified namespace) (both classes refer to each other, so adding them both at once removes the dependency issues), removing the `DebuggerDisplay` and any instances of `Debug.Assert`

You can then parse a *.prd by doing the following

```powershell
Add-Type -Path Z:\SensorHistoryFile.cs
$a = [PrtgAPI.Tests.UnitTests.Support.Data.SensorHistoryFile]::new("Z:\Device 2055.prd")
```

Note: if you get any crashes regarding unknown value types, you may need to add additional rules under `ReadValue` in `SensorHistoryFileChannel`. Most values should be parsed with `ReadInt64`

**Comment by JustinGrote** [comment]
Yeah I basically did what you commented, combined the files due to the cross references. Worked fine.
![image](https://user-images.githubusercontent.com/15258962/77124596-890b8800-6a00-11ea-93ba-fcfcf16a5a4f.png)


On the Type property: Is there an enum for what the different types mean anywhere?

**Comment by lordmilko** [comment]
Obviously there is zero documentation on this anywhere and Paessler would refuse to help me even if I asked. All I know is that `0xCA`, `0xC9`, `0x66` and `0x68` are 8-byte integers, `0xCB` is an 8-byte double, and that `0x2` and `0x3` tend to be used for the `-1` channel (which might actually be `-4` for downtime? No idea)

Maybe these refer to different value types? e.g. a value is actually for a time duration (seconds, minutes, hours, etc), a raw number, a datetime, etc. You can see that there are still a number of bytes I haven't figured out the meaning of, including the property `SensorFileHistory.Unknown` which appears to be a value unique to each PRTG installation.

While I can work around all of these shortcomings for my purposes, as you can see from the namespace I don't currently plan on making this a publicly accessible interface available in PrtgAPI

**Comment by JustinGrote** [comment]
Sure of course, I'm sure I can build an enum as I go, was just curious. Thanks for what you did so far! This will likely help a ton.

**Comment by lordmilko** [comment]
If you discover any patterns that match up with information found in PRTG, please let me know!

**Comment by JustinGrote** [comment]
I just imported 300MB of a full day of historical data from a server, it only took 7.8 seconds for 5.8 million data points, and that's on my laptop with no threading involved.

``` powershell
measure-command {$data = gci | get-prtgdatafile -ErrorAction silentlycontinue}

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 7
Milliseconds      : 832
Ticks             : 78328429
TotalDays         : 9.06579039351852E-05
TotalHours        : 0.00217578969444444
TotalMinutes      : 0.130547381666667
TotalSeconds      : 7.8328429
TotalMilliseconds : 7832.8429


$data.count
1093
$data.channels.count
5864611
```

So far only data issue I came across is type 69 in channel -1 of the ping sensors, which appears to be a binary flag set. It's the exact same value every single time so I assume it's some sort of flag I'll just ignore :)

**Comment by JustinGrote** [comment]
0x6C is another one I came across, it occured on a WMI CPU load sensor. It appears to be an error type and includes the error code, because the value matches the error message.
![image](https://user-images.githubusercontent.com/15258962/77187271-72614180-6a91-11ea-838e-038f7b0e11d6.png)

![image](https://user-images.githubusercontent.com/15258962/77187384-9e7cc280-6a91-11ea-8d10-56ec1a004e0d.png)

**Comment by JustinGrote** [comment]
Now that i have all the exceptions handled, 6.5M records in 4.9 seconds :)

**Comment by lordmilko** [comment]
Thanks @JustinGrote,

Good to know about case `0x6C`; in the PRTG Historical Data page for that time does it show the value as 0 then? I might need to add a pseudo-field for storing the error code so mathematical operations on the `Value` aren't skewed by the presence of error codes

**Comment by lordmilko** [comment]
Also, given you're saying `0x6C` means an error, I reckon I've erroneously dismissed `0x66` and `0x68` as not being errors as well; might be worth removing them or checking what they were about any times they occurred

**Comment by JustinGrote** [comment]
It's not a zero, it's actually the specific error code. Look at the screen shots, the number of the error (end of the message) lines up with the value of the data.

**Comment by lordmilko** [comment]
Those screenshots show what is in the prd and what the display message is. My question is what is displayed on the historical information tab for the channel in question

![image](https://user-images.githubusercontent.com/6138789/77213762-1fa28b00-6b60-11ea-9ab2-7181b8391970.png)

**Comment by JustinGrote** [comment]
Oh I see what you're asking, here it is:
![image](https://user-images.githubusercontent.com/15258962/77214523-cccbc380-6acc-11ea-9f4e-b3635be057cd.png)

**Comment by lordmilko** [comment]
Plan B: if you do `Get-SensorHistory -Raw` on this time period, does it show as 0?

**Comment by JustinGrote** [comment]
returned a $null result, not 0
![image](https://user-images.githubusercontent.com/15258962/77214590-292ee300-6acd-11ea-986c-1d6690622312.png)

**Comment by lordmilko** [comment]
Ah that makes more sense. Thanks!

**Comment by JustinGrote** [comment]
6C seems to be WMI specific. Here's the list of error codes, could build an ENUM out of them:
https://kb.paessler.com/en/topic/1093-my-wmi-sensors-show-errors-with-a-pe-code-what-does-that-mean

**Comment by JustinGrote** [comment]
Actually not, I forced one of the other errors on this list (PE231) and it showed up with the same 6C type
https://kb.paessler.com/en/topic/32813-what-does-error-code-pexxx-mean

**Comment by lordmilko** [comment]
To use an enum, when the `Type` is an error type (like `0x6C`) instead of assigning the value to `Value`, we convert it to a `PEError` which we store in the `Error` pseudo-property and set the `Value` to `null` instead

```c#
enum PEError
{
    IPMismatch = 1
   ...
}
```

**Comment by lordmilko** [comment]
How many *.prd files have you been parsing here? It takes me 17 seconds to parse all 71 files that exist for a specific device and I consume a tonne of memory. In total these give me 15,432,886 channel records; this is sort of in line with the numbers you've presented. In total these files consume about 417mb; based on your numbers I should be able to parse this in 10-11 seconds

**Comment by JustinGrote** [comment]
@lordmilko FYI I've been working on this, and I'm a lot better at C# than I was 3+ years ago :). 

I rewrote the entries read part into an enumerable so files can be read on demand and not at creation, and restructured the entry classes into records so that they can be value compared. I also want to integrate system.io.pipelines for buffer management, and possibly rewrite the record fetch as an IAsyncEnumerable but not sure how much that will help.

Thanks for all your help so far.

https://github.com/JustinGrote/PRTGHistory

**Comment by lordmilko** [comment]
Hi @JustinGrote,

As these come from PrtgAPI can you please ensure your repo contains a *Third Party Notices* file that attributes these files to PrtgAPI, and includes a copy of PrtgAPI's license found [here](https://github.com/lordmilko/PrtgAPI/blob/master/LICENSE)

**Comment by JustinGrote** [comment]
> Hi @JustinGrote,
> 
> As these come from PrtgAPI can you please ensure your repo contains a *Third Party Notices* file that attributes these files to PrtgAPI, and includes a copy of PrtgAPI's license found [here](https://github.com/lordmilko/PrtgAPI/blob/master/LICENSE)

Yep absolutely! Was a first commit but I definitely need to get the license in there. 
EDIT: DONE!
