### ISSUE TITLE
PRTG stops responding when a WMI Service sensor is created

### ISSUE THREAD

**Issue by DenisBessa** [lordmilko/PrtgDocker#2]
The Core.log file, located under /logs/core folder, displays:
2020-03-27 12:30:53.305576 ERRR TId    1688 Core> Graph: Access violation at address 00007FFDCAE6C6D1 in module 'chartdir60.dll'. Read of address 0000000000000008 (State=16,0)

**Comment by lordmilko** [comment]
How are you creating the sensor, which sensor type are you creating and which version of PRTG Docker are you using? I just successfully created a DHCP Client WMI Service sensor on a container running 19.4.54

**Comment by DenisBessa** [comment]
Thanks for your response.

I'm using the 20.1.57.1745 x64 version.

I could reproduce the error wen trying to create the WMI Free Disk Space sensor from the admin console.

**Comment by lordmilko** [comment]
I don't currently have a Docker image for 20.1.57.1745 on Docker Hub, so are you able to confirm if this is a Docker image you created yourself?

If so, are you able to confirm that you used the PrtgDocker.ps1 script to create this image?

One of the issues with using PRTG in Docker is that the Server 2019 images have stripped all fonts from the system. Chart Director assumes the existence of some of these fonts for drawing charts in the PRTG UI, and will crash of these fonts are not installed. PrtgDocker.ps1 automatically installs all of the required fonts for you to work around this issue. It does this by copying these fonts from your local computer to the Docker image when the image is created. If you don't have any fonts for Tahoma or Arial under C:\Windows\Fonts on the server where you created this image, this could explain why the fonts are also missing inside of Docker

I created a 20.1.57.1745 image on my computer and am not having any issues when I view charts or try and create these types of sensors

**Comment by DenisBessa** [comment]
Thanks again for the help!

For some reason, the .tff files were not copied to the container. I manually copied them to the build folder and now everything is working!

**Comment by lordmilko** [comment]
The script uses the folder %temp%\dockerTemp as the build folder. All of the fonts should be automatically copied over there during the build.

Are you able to advise what the output of

```powershell
C:\Windows\Fonts | where {$_.Name -like "*arial*" -or $_.Name -like "*tahoma*" }
```

is? Or otherwise, what are your *.tff files called? I would like to fix whatever caused this issue for you so that other users don't run into it in the future

**Comment by DenisBessa** [comment]
The output is:

-a----        9/15/2018   4:12 AM        1036584 arial.ttf
-a----        9/15/2018   4:12 AM         980756 arialbd.ttf
-a----        9/15/2018   4:12 AM         721144 arialbi.ttf
-a----        9/15/2018   4:12 AM         717428 ariali.ttf
-a----        9/15/2018   4:12 AM         939280 tahoma.ttf
-a----        9/15/2018   4:12 AM         867988 tahomabd.ttf

Apparently, the problem is copying the files to the build folder.
