### ISSUE TITLE
File Path Error

### ISSUE THREAD

**Issue by trixrahbit** [lordmilko/PrtgDocker#3]
Build 20.1.57.1786 throw an error at like line 925 for a missing c:\program files(x86)\webroot path

**Comment by lordmilko** [comment]
Hi @trixrahbit,

Are you able to copy and paste the full error description?

I just tested and successfully was able to build version 20.1.57.1786

**Comment by trixrahbit** [comment]
Available Commands:
    New-PrtgBuild
    New-PrtgContainer
    Get-PrtgImage
PS E:\prtg> New-PrtgBuild
Enumerating installers in 'E:\PRTG'
Identified the following installers for processing

prtg_installer_with_trial_key_000014-04UKFM-8FFJMP-1603KR-2K70HV-98KG6F-C4J1G9-A6RE74-860PV0-U9AHTF.exe
$env:DOCKER_HOST is not defined. Assuming running from Docker server
Processing version '20.1.57.1786'
Executing 'docker build C:\Users\cti-ab\AppData\Local\Temp\dockerTemp -t
prtg:20.1.57 --build-arg BASE_IMAGE=
mcr.microsoft.com/windows/servercore:ltsc2019'
Sending build context to Docker daemon  289.8MB
Step 1/11 : ARG BASE_IMAGE=mcr.microsoft.com/windows/servercore:ltsc2019
Step 2/11 : FROM $BASE_IMAGE
 ---> 80e84fd280e2
Step 3/11 : SHELL ["powershell", "-Command", "$ErrorActionPreference =
'Stop'; $ProgressPreference = 'SilentlyContinue';"]
 ---> Using cache
 ---> 1b6bb8fde7c1
Step 4/11 : ARG PRTG_INSTALLER_URL
 ---> Using cache
 ---> 2de88b2ea0c3
Step 5/11 : ARG PRTG_EMAIL="prtg@example.com"
 ---> Using cache
 ---> 03209483fb9b
Step 6/11 : ARG PRTG_LICENSENAME="prtgtrial"
 ---> Using cache
 ---> aaf751c8378a
Step 7/11 : ARG
PRTG_LICENSEKEY="000014-250KFM-8FFN6H-31QZ6R-DD7ABX-GE8EQN-CXUU28-1W32K6-RPBM77-W2KV7Y"
 ---> Using cache
 ---> d90ad6874319
Step 8/11 : COPY PrtgDocker.ps1 config.dat* *.exe *.ttf C:/Installer/
 ---> Using cache
 ---> eb6be7ade129
Step 9/11 : RUN Set-ExecutionPolicy Unrestricted;
C:/Installer/PrtgDocker.ps1 -Install
 ---> Running in 510340e026ab
Enumerating installers in 'C:\Installer'
Identified the following installers for processing

prtg_installer_with_trial_key_000014-04UKFM-8FFJMP-1603KR-2K70HV-98KG6F-C4J1G9-A6RE74-860PV0-U9AHTF.exe
Executing
'C:\Installer\prtg_installer_with_trial_key_000014-04UKFM-8FFJMP-1603KR-2K70HV-98KG6F-C4J1G9-A6RE74-860PV0-U9AHTF.exe
/verysilent /adminemail="prtg@example.com" /SUPPRESSMSGBOXES
/log="C:\Installer\log.log"
/licensekey="000014-250KFM-8FFN6H-31QZ6R-DD7ABX-GE8EQN-CXUU28-1W32K6-RPBM77-W2KV7Y"
/licensekeyname="prtgtrial" /NoInitialAutoDisco=1'
    Installer completed with exit code -1073741511
Checking required fonts are installed
    Installing font 'arial.ttf'
    Installing font 'arialbd.ttf'
    Installing font 'arialbi.ttf'
    Installing font 'ariali.ttf'
    Installing font 'tahoma.ttf'
    Installing font 'tahomabd.ttf'
Disabling UI nags
Set-Content : Could not find a part of the path 'C:\Program Files (x86)\PRTG
Network Monitor\webroot\css\styles_custom_v2.css'.
At C:\Installer\PrtgDocker.ps1:925 char:9
+         Set-Content $stylesPath $str
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program
File...s_custom_v2.c
   ss:String) [Set-Content], DirectoryNotFoundException
    + FullyQualifiedErrorId :
GetContentWriterDirectoryNotFoundError,Microsoft
   .PowerShell.Commands.SetContentCommand

The command 'powershell -Command $ErrorActionPreference = 'Stop';
$ProgressPreference = 'SilentlyContinue'; Set-ExecutionPolicy Unrestricted;
C:/Installer/PrtgDocker.ps1 -Install' returned a non-zero code: 1
docker build did not complete successfully. Most failures relate to subtle
timing issues during build; please try
running build again
At E:\PRTG\PrtgDocker.ps1:456 char:9
+         throw "docker build did not complete successfully. Most failu ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (docker build di...ing
build again:String) [], RuntimeException
    + FullyQualifiedErrorId : docker build did not complete successfully.
Most failures relate to subtle timing issues
    during build; please try running build again

**Comment by lordmilko** [comment]
Hi @trixrahbit,

I can see that actually the issue is that PRTG is not installing properly for some reason

```
Installer completed with exit code -1073741511
```

Can you please
1. Download the attached file
2. Change the extension from *.txt to *.ps1
3. Place this under E:\prtg
4. Rerun `build.cmd` with the command `New-PrtgBuild`

This time when it fails it will output the PRTG installation log, which should detail why exactly the installation failed

[PrtgDocker.txt](https://github.com/lordmilko/PrtgDocker/files/4437393/PrtgDocker.txt)

**Comment by trixrahbit** [comment]
I felt like that too. It doesn’t seem to run the execution and therefore
getting to the webroot directory for the styles it fails. I’ll get this ran
and let you know.

**Comment by lordmilko** [comment]
Hi @trixrahbit,

How did you go with this?

**Comment by trixrahbit** [comment]
I have been swamped. Thanks this actually reminds me I need to circle back
to this
