### ISSUE TITLE
Is this available for linux?

### ISSUE THREAD

**Issue by GlenBleidd** [lordmilko/PrtgDocker#4]
Noob question, as the title says, can I set this up on CentOS 8? We are planning to migrate things from Windows to Linux, and since I can't install PRTG on linux, I was trying to set it up on a dcoker container instead...

**Comment by lordmilko** [comment]
Hi @GlenBleidd,

My understanding is that Windows Docker containers are not supported on Linux, as such images produced by this project will not work in Linux either.

In the event support for running Windows containers on Linux is added, images produced by this project should be able to run on Linux

**Comment by GlenBleidd** [comment]
Understood, thank you!
