### ISSUE TITLE
PrtgDocker on Docker 20.10.3 (linux/amd64)

### ISSUE THREAD

**Issue by amacons** [lordmilko/PrtgDocker#6]
lordmilko hi,
as far as I understood from previous requests, PrtgDocker runs a Windows-based Container, since PRTG is only developed for Windows, and therefore can not be used on a Linux-based Docker system without Windows support option. Correct?
Thanks
Alex

**Comment by lordmilko** [comment]
Correct

**Comment by amacons** [comment]
Ok, thanks.

Is there an approach creating another image based on the use of wine, as mentioned by PRTG?

**Comment by lordmilko** [comment]
I'm not aware of any such approach however you can potentially leverage the PRTG Core Server/PRTG Probe installation commands outlined in the dockerfiles of this repo.

Separately to this, PRTG does have a [multi-platform probe](https://kb.paessler.com/en/topic/90140-what-is-the-multi-platform-probe-and-how-can-i-use-it) available now which you could potentially also look at containerizing, however this underscores an important point which is that regardless of whether you manage to get PRTG services running on Linux or not, I would imagine many components such as WMI would not work

**Comment by amacons** [comment]
To be correct, the wine approach comes from the PRTG founder's blog and goes back to the [PRTG Traffic Grapper](https://blog.paessler.com/running-prtg-traffic-grapher-on-a-linux-computer). 

I'd be happy to take a look at the installation commands from the PRTG Core Server/PRTG Probe in the dockfiles of your repo.

It is quite possible that some sensors cannot really be used when operating PRTG under Linux because the necessary Windows basis is missing.

Thanks for the information and the exchange of views.
