### ISSUE TITLE
General questions and discussion

### ISSUE THREAD

**Issue by JJWatMyself** [lordmilko/PrtgDocker#7]
Very interested to test this in the coming weeks. I have often thought about container approach to PRTG Core / Probe and decouple from dedicated Windows OS.  Is it safe to say this solves the problem of multiple instances of PRTG Core on the same Windows OS?  In addition because it is Docker, ability to use macvlan for dedicated IP addresses per instance of PRTG?

**Comment by lordmilko** [comment]
You can run several instances of the PRTG Core server and/or PRTG Probe on a single Windows Server

I haven't used macvlan so I can't comment in that regard

**Comment by JJWatMyself** [comment]
Thanks for confirming.  This will be really helpful to scale the home lab. Value of macvlan it creates an internal vswitch, bridged to the same NIC as the OS.  I use this on Synology with Docker. I'm sure macvlan is more powerful but being able to have dedicated IP address on each container works well. I also found there is value in setting specific files/folders to be external to the container.  This way the contents of the container are pretty irrelevant beyond the code itself.  That might just be my preference.  e.g. programdata, maybe some other folders where custom files are stored, like device templates and scripts. Have you looked into that with PRTG in Docker?

**Comment by lordmilko** [comment]
PrtgDocker natively supports redirecting the *Custom Sensors* folder to a Docker Volume or symlinking to a UNC path

Please see the [wiki](https://github.com/lordmilko/PrtgDocker/wiki/Advanced) for further details

If you copied all of the default files that exist in a other unsupported directories to an external folder, you could presumably create volumes for those directories as well, however if you wanted to use symlinks to UNC paths you would perhaps need to augment the image build system to support generating these symlinks

**Comment by JJWatMyself** [comment]
I have to say, what you've done here is ground-breaking. I asked support about this a number of years ago. Initially as a way to get it off Windows. You already know what the outcome of that conversation was.  Looking forward to getting some time set aside to work with this in one of these upcoming weekends.  I have my PRTG home lab running on a VM on Synology at the moment.  Likely will be vacating the Synology and doing some things with Proxmox.  Using this is going to make it a lot more fun! 

I recently forked a simple custom webhook script, as PRTG is lacking and the original was outdated.  PRTG notifications in Discord is pretty handy. I am not altogether sure if PS will run in Docker on Windows though.  What do you think?

https://github.com/JJWatMyself/prtg-notifications-discord

**Comment by lordmilko** [comment]
PrtgDocker executes a PowerShell script in the container in order to set everything up in the first place, so I can confirm PowerShell does work in Windows Docker images

**Comment by JustinGrote** [comment]
I'm working to adapt this to Azure Container Registry and Azure Container Images so I can just spin them up on demand as I need them. Thanks for laying the groundwork!

@lordmilko FYI, I believe your docker hub images, even tho they are 3 years old, include the PRTG bits. That's technically a violation of the redistribution license (page 2), so you may want to remove those.
https://hlassets.paessler.com/common/files/pdf/terms/20181115_terms-license-us_en.pdf

**Comment by lordmilko** [comment]
I am not in the USA, as such the linked document does not apply to me

As per the license terms for non-USA (found here https://www.paessler.com/company/terms) I believe the Docker Hub images are permitted as per Section 6 (pertaining to the freeware/trial edition).

I am going to close this issue for now; for any specific further queries please open a new issue
